- name: cicdtest
  hosts: master
  gather_facts: no

  tasks:
    - name: Clone repository
      git:
        repo: 'https://github.com/hyunn-n/cicdtest.git'
        dest: /root
        clone: yes
        update: yes
