apiVersion: apps/v1
kind: Deployment
metadata:
  name: grweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grweb
  template:
    metadata:
      labels:
        app: grweb
    spec:
      containers:
        - name: grweb
          image: hynnx/cicdtest:Green
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: grweb
spec:
  type: LoadBalancer
  selector:
    app: grweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
